version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx.Dockerfile
    ports:
      - 8098:80
    volumes:
      - ./api:/var/www/symfony-docker
    links:
      - fpm
      - mysql
  fpm:
    build:
      context: .
      dockerfile: docker/fpm/fpm.Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./api:/var/www/symfony-docker
    depends_on:
      - mysql
    links:
      - mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootroot
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: api 
  node:
    build: ./docker/node
    ports:
      - "4200:4200"
    volumes:
      - ./front:/var/www/front:cached
      - /var/www/front/node_modules/
